"""
For lack of time, I will not research how to delete the default CRUD permissions
nor how to edit the default permission names to match what I want them to do.

Instead I'm just going to list all the default CRUD permissions here so that I can
"hide" them in the create/edit groups page.

I will create custom permissions to handle all of Covigo's access control. These
permissions will have more descriptive names and will be shown in the create/edit
groups page.
"""

DEFAULT_PERMISSIONS = (
    'add_flag',
    'change_flag',
    'delete_flag',
    'view_flag',
    'add_patient',
    'change_patient',
    'delete_patient',
    'view_patient',
    'add_profile',
    'change_profile',
    'delete_profile',
    'view_profile',
    'add_staff',
    'change_staff',
    'delete_staff',
    'view_staff',
    'add_logentry',
    'change_logentry',
    'delete_logentry',
    'view_logentry',
    'add_appointment',
    'change_appointment',
    'delete_appointment',
    'view_appointment',
    'add_group',
    'change_group',
    'delete_group',
    'view_group',
    'add_permission',
    'change_permission',
    'delete_permission',
    'view_permission',
    'add_user',
    'change_user',
    'delete_user',
    'view_user',
    'add_code',
    'change_code',
    'delete_code',
    'view_code',
    'add_contenttype',
    'change_contenttype',
    'delete_contenttype',
    'view_contenttype',
    'add_messagecontent',
    'change_messagecontent',
    'delete_messagecontent',
    'view_messagecontent',
    'add_messagegroup',
    'change_messagegroup',
    'delete_messagegroup',
    'view_messagegroup',
    'add_staticdevice',
    'change_staticdevice',
    'delete_staticdevice',
    'view_staticdevice',
    'add_statictoken',
    'change_statictoken',
    'delete_statictoken',
    'view_statictoken',
    'add_totpdevice',
    'change_totpdevice',
    'delete_totpdevice',
    'view_totpdevice',
    'add_session',
    'change_session',
    'delete_session',
    'view_session',
    'add_patientsymptom',
    'change_patientsymptom',
    'delete_patientsymptom',
    'view_patientsymptom',
    'add_symptom',
    'change_symptom',
    'delete_symptom',
    'view_symptom',
    'add_phonedevice',
    'change_phonedevice',
    'delete_phonedevice',
    'view_phonedevice'
 )