# Generated by Django 4.0.2 on 2022-02-12 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_flag_flag_unique_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs_flagged_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flag',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
