# Generated by Django 4.0.2 on 2022-03-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_address_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='availability_slot_generator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
