# Generated by Django 4.0.2 on 2022-03-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staff_availability_slot_generator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='availability_slot_generator',
        ),
    ]
