# Generated by Django 4.0.2 on 2022-03-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_staff_availability_slot_generator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='staff',
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.staff'),
        ),
    ]
