# Generated by Django 4.0.2 on 2022-03-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_patient_staff_patient_assigned_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to='accounts.staff'),
        ),
    ]
