# Generated by Django 4.0.2 on 2022-03-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_patient_assigned_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='is_recovered',
            new_name='is_negative',
        ),
    ]
