# Generated by Django 4.0.2 on 2022-03-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
