# Generated by Django 4.0.2 on 2022-03-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_is_recovered_patient_is_negative'),
        ('accounts', '0011_delete_code'),
    ]

    operations = [
    ]
