# Generated by Django 4.0.2 on 2022-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='violation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
