# Generated by Django 4.0.2 on 2022-03-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_preferences'),
        ('accounts', '0012_merge_20220322_1647'),
    ]

    operations = [
    ]
