# Generated by Django 4.0.2 on 2022-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_patient_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='violation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
