# Generated by Django 4.0.2 on 2022-04-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_violation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('edit_self', 'Can edit their own user'), ('cancel_appointment', 'Can cancel an appointment'), ('edit_username', 'Can edit their username'), ('edit_name', 'Can edit their first and last name'), ('edit_email', 'Can edit their email address'), ('edit_phone', 'Can edit their phone number'), ('edit_address', 'Can edit their address and postal code'), ('system_message_preference', 'Can edit their system message preference'), ('status_deadline_reminder_preference', 'Can edit their status update deadline reminder preference'), ('appointment_reminder_preference', 'Can edit their appointment reminder preference')]},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('is_doctor', 'Staff member is a doctor user'), ('flag_assigned', 'Can flag assigned patients'), ('flag_patients', 'Can flag any patient'), ('flag_view_all', 'Can view all assigned flags'), ('create_patient', 'Can add a patient user'), ('create_user', 'Can add any user'), ('edit_assigned', 'Can edit assigned patients'), ('edit_patient', 'Can edit any patient'), ('edit_user', 'Can edit any user'), ('remove_availability', 'Can delete an appointment availability'), ('manage_groups', 'Can create a new group or edit existing groups'), ('assign_group', "Can edit a new or existing user's assigned groups"), ('message_assigned', 'Can compose a new message with assigned patients'), ('message_patient', 'Can compose a new message with any patient'), ('message_user', 'Can compose a new message with any user'), ('manage_symptoms', 'Can create, edit, enable, or disable symptoms'), ('assign_symptom_assigned', 'Can assign or update symptoms for assigned patients'), ('assign_symptom_patient', 'Can assign or update symptoms for any patient'), ('dashboard_covigo_data', 'Can view Covigo case data in dashboard'), ('dashboard_external_data', 'Can view external case data in dashboard'), ('view_patient_code', "Can view any patient's QR and patient code"), ('set_patient_case', "Can edit any patient's case status (confirmed and latest test)"), ('set_patient_quarantine', "Can edit any patient's quarantine status"), ('view_patient_test_report', "Can view any patient's test report"), ('view_assigned_code', "Can view an assigned patient's QR and patient code"), ('set_assigned_case', "Can edit an assigned patient's case status (confirmed and latest test)"), ('set_assigned_quarantine', "Can edit an assigned patient's quarantine status"), ('view_assigned_test_report', "Can view an assigned patient's test report"), ('view_assigned_doctor', "Can view any patient's assigned doctor"), ('edit_assigned_doctor', 'Can manage doctor patient assignments and reassign a patient to any other doctor'), ('view_assigned_patients', "Can view a doctor's assigned patients"), ('view_manager_data', 'Can view the data in the Management page'), ('edit_preference_user', "Can edit another user's preferences"), ('view_assigned_list', 'Can view their assigned patients in Accounts page'), ('view_patient_list', 'Can view all patients in Accounts page'), ('view_user_list', 'Can view all users in the Accounts page'), ('view_flagged_user_list', 'Can view flagged users in the Accounts page'), ('manage_contact_tracing', 'Can access the contact tracing management page'), ('manage_case_data', 'Can access the case data management page'), ('view_patient_appointment', "Can view any patient's upcoming appointments"), ('view_user_appointment', "Can view any user's upcoming appointments")]},
        ),
    ]
