# Generated by Django 4.0.2 on 2022-03-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsymptom',
            name='is_viewed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
