# Generated by Django 4.0.2 on 2022-02-12 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='users',
            field=models.ManyToManyField(related_name='symptoms', through='symptoms.PatientSymptom', to=settings.AUTH_USER_MODEL),
        ),
    ]
