# Generated by Django 4.0.2 on 2022-04-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_patientsymptom_status_alter_patientsymptom_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsymptom',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
