# Generated by Django 4.0.2 on 2022-03-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_patientsymptom_status_alter_patientsymptom_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsymptom',
            name='browser_user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
