# Generated by Django 4.0.2 on 2022-03-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_patientsymptom_browser_user_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsymptom',
            old_name='browser_user_agent',
            new_name='user_agent',
        ),
    ]
