# Generated by Django 4.0.2 on 2022-03-31 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0005_rename_browser_user_agent_patientsymptom_user_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsymptom',
            old_name='user_agent',
            new_name='browser_user_agent',
        ),
    ]
