# Generated by Django 4.0.2 on 2022-04-02 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0006_rename_user_agent_patientsymptom_browser_user_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsymptom',
            old_name='browser_user_agent',
            new_name='user_agent',
        ),
    ]
