# Generated by Django 4.0.2 on 2022-02-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagegroup',
            old_name='seen',
            new_name='author_seen',
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='recipient_seen',
            field=models.BooleanField(default=False),
        ),
    ]
