# Generated by Django 4.0.2 on 2022-03-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_seen_messagegroup_author_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroup',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
