name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Activate venv
      run: |
        if [ ! -d "/venv/" ]; then virtualenv venv; fi
        source venv/bin/activate
    - name: Install Dependencies
      run: |
        
        pip3 install --upgrade pip
        pip3 install django
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Run Tests
      run: |
        python3.10 manage.py test