name: Django Tests CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Activate venv
      run: |
        if [ ! -d "/venv/" ]; then virtualenv venv; fi
        source venv/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
    - name: Install Dependencies
      run: |
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        pip3 install --upgrade pip
        pip3 install django
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; 
        
    - name: Run Tests
      env:
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: |
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        python3.10 manage.py test
    - name: Deactivate venv
      run: |
        deactivate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV