name: Run Tests
on:
  workflow_call:
    secrets:
      DATABASE_USER:
        required: true
      DATABASE_PASSWORD:
        required: true

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      env:
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: |
        if [ ! -d "/venv/" ]; then virtualenv venv; fi
        source venv/bin/activate
        pip3 install --upgrade pip
        pip3 install django
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        python3.10 manage.py test