name: Django CI
on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/tests